// src/boards/profiles.js
export const BOARDS = {
  docker: {
    id: 'docker',
    name: 'Docker',
    modules: [
      'docker_basics',
      'docker_install',
      'docker_images',
      'docker_containers',
      'docker_lifecycle',
      'docker_logs_exec',
      'docker_volumes_cli',
      'docker_networks',
      'docker_registry',
      'docker_compose',
      'docker_build',
      'docker_contexts',
      'docker_system',
      'docker_advanced',
      'docker_swarm',
      'docker_security',
      'docker_troubleshooting'
    ],
  },
  jenkins: {
    id: 'jenkins',
    name: 'Jenkins',
    modules: [
      'jenkins_pipeline_basics',
      'jenkins_cli',
      'jenkins_jobs',
      'jenkins_artifacts',
      'jenkins_pipeline_steps',
      'jenkins_agents',
      'jenkins_credentials',
      'jenkins_admin',
      'jenkins_rest_api',
      'jenkins_groovy',
      'jenkins_logs',
      'jenkins_backup',
      'jenkins_recipes',
      'jenkins_scripted_pipeline',
      'jenkins_declarative_pipeline',
      'cicd_scenarios'
    ],
  },
  linux: {
    id: 'linux',
    name: 'Linux',
    modules: [
      'linux_shell_basics',
      'linux_file_system_ops',
      'linux_text_view_edit',
      'linux_searching',
      'linux_text_processing',
      'linux_permissions_acls',
      'linux_archiving',
      'linux_processes_jobs',
      'linux_system_info',
      'linux_disk_storage',
      'linux_networking',
      'linux_dns_tools',
      'linux_ssh_remote',
      'linux_package_managers',
      'linux_services_logs',
      'linux_scheduling',
      'linux_users_groups',
      'linux_disk_io',
      'linux_processes_fds',
      'linux_debugging_tracing',
      'linux_security_crypto',
      'linux_firewall',
      'linux_filesystem_attributes'
    ],
  },
  ansible: {
    id: 'ansible',
    name: 'Ansible',
    modules: [
        'ansible_playbooks',
        'ansible_cli',
        'ansible_adhoc',
        'ansible_core_modules',
        'ansible_roles',
        'ansible_vault'
    ],
  },
  terraform: {
    id: 'terraform',
    name: 'Terraform',
    modules: [
      'terraform',
      'terraform_basics',
      'terraform_cli',
      'terraform_state',
      'terraform_workspaces',
      'terraform_resources',
      'terraform_providers',
      'terraform_backends',
      'terraform_variables_outputs',
      'terraform_automation',
      'terraform_cloud',
      'terraform_advanced_state',
      'terraform_testing',
      'terraform_recipes',
      'terraform_inspection',
      'terraform_locking',
      'terraform_security',
      'terraform_modules',
      'terraform_env_variables',
      'terraform_destructive'
    ],
  },
};

export const DEFAULT_BOARD_ID = 'docker';
