# python/blocks_runtime.py

"""
A secure runtime for executing code generated by the Blockly environment.

This module provides a set of safe, sandboxed helper functions that can be
called by the generated Python code. The goal is to prevent unsafe operations
such as arbitrary file access, unrestricted network requests, or dangerous
system-level calls.

All block-generated code that requires a complex or potentially unsafe operation
should delegate that operation to a function in this module.
"""

import enum
import typing
import collections.abc
import functools
import concurrent.futures
import atexit
import os
import json
import csv
import io
import sqlite3
import inspect

# --- Core Fundamentals Runtime Helpers ---

def create_enum(name: str, members: list):
    """Safely creates an Enum class."""
    if not isinstance(name, str) or not all(isinstance(m, str) for m in members):
        return enum.Enum(name, [])
    return enum.Enum(name, {member: member for member in members})

def create_dataclass(name: str, fields: list):
    """Safely creates a dataclass."""
    if not isinstance(name, str) or not all(isinstance(f, str) for f in fields):
        return None
    from dataclasses import dataclass
    new_type = type(name, (), {'__annotations__': {field: typing.Any for field in fields}})
    return dataclass(new_type)

def create_namedtuple(name: str, field_names: list):
    """Safely creates a namedtuple."""
    if not isinstance(name, str) or not all(isinstance(f, str) for f in field_names):
        return None
    return collections.namedtuple(name, field_names)

# --- Records & Structs Runtime Helpers ---

def create_dataclass_with_defaults(name: str, fields: list, defaults: dict):
    """Safely creates a dataclass with default values."""
    from dataclasses import make_dataclass, field
    if not isinstance(name, str) or not all(isinstance(f, str) for f in fields):
        return None

    field_definitions = []
    for f in fields:
        if f in defaults:
            field_definitions.append((f, typing.Any, field(default=defaults[f])))
        else:
            field_definitions.append((f, typing.Any))

    return make_dataclass(name, field_definitions)

def record_to_dict(record):
    """Converts a namedtuple or dataclass instance to a dictionary."""
    if hasattr(record, '_asdict'): # Check for namedtuple
        return record._asdict()
    from dataclasses import is_dataclass, asdict
    if is_dataclass(record):
        return asdict(record)
    return {}

# --- Math Runtime Helpers ---

def _is_prime(n):
    """Checks if a number is prime. Helper for the num_property block."""
    if not isinstance(n, int):
        return False
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# --- i18n Translation Runtime ---

_translation_registry = {}

def register_translation(lang: str, translations: dict):
    """Registers a dictionary of translations for a given language."""
    if not isinstance(lang, str) or not isinstance(translations, dict):
        return
    _translation_registry.setdefault(lang, {}).update(translations)

def translate(key: str, lang: str, fallback: str = None) -> str:
    """Translates a key into the given language."""
    if lang is None:
        lang = get_locale()
    if fallback is None:
        fallback = key
    return _translation_registry.get(lang, {}).get(key, fallback)

_current_locale = 'en'

def set_locale(lang: str):
    """Sets the current locale for translations."""
    global _current_locale
    _current_locale = lang

def get_locale() -> str:
    """Gets the current locale."""
    return _current_locale

def pluralize(key: str, n: int, lang: str = None) -> str:
    """
    Handles basic pluralization. Assumes keys like 'item' and 'item_plural'.
    A real implementation would use a more robust library.
    """
    if lang is None:
        lang = get_locale()

    if n == 1:
        return translate(key, lang)
    else:
        return translate(f"{key}_plural", lang, fallback=translate(key, lang) + 's')

def generate_alt_text(metadata: dict, lang: str = None) -> str:
    """Generates a simple alt text from image metadata."""
    if lang is None:
        lang = get_locale()

    description = metadata.get('description', 'An image')
    return translate(description, lang)

def remove_accents(input_str):
    """Removes accents from a string."""
    import unicodedata
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

def slugify(value):
    """
    Converts to lowercase, removes non-word characters (alphanumerics and
    hyphens) and converts spaces to hyphens. Also strips leading and
    trailing whitespace.
    """
    import re
    value = remove_accents(value)
    value = re.sub(r'[^\w\s-]', '', value).strip().lower()
    return re.sub(r'[-\s]+', '-', value)

def fix_encoding(text):
    """
    Fixes mojibake and other encoding issues in text.
    Requires the 'ftfy' library.
    """
    try:
        import ftfy
        return ftfy.fix_text(text)
    except ImportError:
        return "Error: The 'ftfy' library is required for this block."

def render_jinja(template_str, context):
    """Renders a Jinja2 template."""
    try:
        from jinja2 import Template
        template = Template(template_str)
        return template.render(context)
    except ImportError:
        return "Error: The 'jinja2' library is required for this block."
    except Exception as e:
        return f"Error rendering template: {e}"

def render_safe_template(template_str, context):
    """Renders a Jinja2 template in a sandboxed environment."""
    try:
        from jinja2 import SandboxedEnvironment
        env = SandboxedEnvironment()
        template = env.from_string(template_str)
        return template.render(context)
    except ImportError:
        return "Error: The 'jinja2' library is required for this block."
    except Exception as e:
        return f"Error rendering safe template: {e}"

# --- Dictionary & Mapping Runtime Helpers ---

def deep_merge(d1, d2):
    """Recursively merges two dictionaries."""
    for k, v in d2.items():
        if k in d1 and isinstance(d1[k], dict) and isinstance(v, collections.abc.Mapping):
            d1[k] = deep_merge(d1[k], v)
        else:
            d1[k] = v
    return d1

def get_nested(d, path, default=None):
    """Safely gets a value from a nested dictionary using a list of keys."""
    if not isinstance(d, dict) or not isinstance(path, list):
        return default
    for key in path:
        if not isinstance(d, dict) or key not in d:
            return default
        d = d[key]
    return d

def set_nested(d, path, value):
    """Safely sets a value in a nested dictionary using a list of keys."""
    if not isinstance(d, dict) or not isinstance(path, list):
        return
    for key in path[:-1]:
        d = d.setdefault(key, {})
    d[path[-1]] = value

def flatten_dict(d, parent_key='', sep='.'):
    """Flattens a nested dictionary."""
    items = []
    for k, v in d.items():
        new_key = parent_key + sep + k if parent_key else k
        if isinstance(v, collections.abc.Mapping):
            items.extend(flatten_dict(v, new_key, sep=sep).items())
        else:
            items.append((new_key, v))
    return dict(items)

def unflatten_dict(d):
    """Unflattens a dictionary with dot-separated keys."""
    result = {}
    for k, v in d.items():
        parts = k.split('.')
        d_nested = result
        for part in parts[:-1]:
            d_nested = d_nested.setdefault(part, {})
        d_nested[parts[-1]] = v
    return result

# --- Function & Callable Runtime Helpers ---

def wraps(wrapped):
    """A pass-through for functools.wraps to be used by decorator blocks."""
    return functools.wraps(wrapped)

# --- Iterator & Generator Runtime Helpers ---

def safe_next(iterator, default=None):
    """Safely gets the next item from an iterator."""
    try:
        return next(iterator)
    except StopIteration:
        return default

# --- Loop & Iteration Runtime Helpers ---

class LoopLimitExceeded(Exception):
    """Custom exception for loops that run too long."""
    pass

def limited_iterator(iterable, max_iterations=1000):
    """A generator that wraps an iterable and limits the number of iterations."""
    count = 0
    iterator = iter(iterable)
    while True:
        if count >= max_iterations:
            raise LoopLimitExceeded(f"Loop exceeded maximum of {max_iterations} iterations.")
        try:
            yield next(iterator)
            count += 1
        except StopIteration:
            return

def sliding_window(sequence, size, step):
    """Returns a list of sliding windows over a sequence."""
    if size <= 0 or step <= 0:
        return []
    return [sequence[i:i+size] for i in range(0, len(sequence) - size + 1, step)]

# --- Concurrency & Parallelism Runtime Helpers ---

MAX_WORKERS = 4
_executor = concurrent.futures.ThreadPoolExecutor(max_workers=MAX_WORKERS)
atexit.register(lambda: _executor.shutdown(wait=True))

def thread_start(func, args=()):
    """Starts a new thread."""
    import threading
    thread = threading.Thread(target=func, args=args)
    thread.start()
    return thread

def thread_join(thread):
    """Waits for a thread to complete."""
    if thread:
        thread.join()

def submit_task(func, *args, **kwargs):
    """Submits a task to the global thread pool."""
    if not callable(func):
        raise TypeError("Only callable objects can be submitted as tasks.")
    return _executor.submit(func, *args, **kwargs)

def get_future_result(future, timeout=None):
    """Gets the result from a future object."""
    if not isinstance(future, concurrent.futures.Future):
        return "Invalid input: not a future object."
    try:
        return future.result(timeout=timeout)
    except concurrent.futures.TimeoutError:
        return "Timeout: Task did not complete in time."
    except Exception as e:
        return f"Task failed with an exception: {e}"

def is_future_done(future):
    """Checks if a future is done."""
    if not isinstance(future, concurrent.futures.Future):
        return False
    return future.done()

# --- Filesystem & I/O Runtime Helpers ---

class VirtualFileSystem:
    """A simple in-memory virtual filesystem."""
    def __init__(self):
        self._fs = {"/": {}}

    def _normalize_path(self, path):
        return os.path.normpath(os.path.join("/", path))

    def _get_node(self, path, create=False):
        parts = self._normalize_path(path).strip("/").split("/")
        node = self._fs["/"]
        for part in parts:
            if not part:
                continue
            if part not in node:
                if create:
                    node[part] = {}
                else:
                    return None
            node = node[part]
        return node

    def write_file(self, path, content):
        if not isinstance(content, str):
            content = str(content)
        dirname, basename = os.path.split(self._normalize_path(path))
        parent_node = self._get_node(dirname, create=True)
        if parent_node is None or not isinstance(parent_node, dict):
            return {"error": "Invalid path"}
        parent_node[basename] = content
        return {"status": "success"}

    def read_file(self, path):
        dirname, basename = os.path.split(self._normalize_path(path))
        parent_node = self._get_node(dirname)
        if parent_node and basename in parent_node and isinstance(parent_node[basename], str):
            return parent_node[basename]
        return {"error": "File not found"}

    def list_dir(self, path):
        node = self._get_node(path)
        if isinstance(node, dict):
            return list(node.keys())
        return {"error": "Directory not found"}

    def append_file(self, path, content):
        if not isinstance(content, str):
            content = str(content)
        current_content = self.read_file(path)
        if isinstance(current_content, dict) and "error" in current_content:
            return self.write_file(path, content)
        return self.write_file(path, current_content + content)

    def delete_file(self, path):
        dirname, basename = os.path.split(self._normalize_path(path))
        parent_node = self._get_node(dirname)
        if parent_node and basename in parent_node:
            del parent_node[basename]
            return {"status": "success"}
        return {"error": "File not found"}

    def file_exists(self, path):
        dirname, basename = os.path.split(self._normalize_path(path))
        parent_node = self._get_node(dirname)
        return parent_node is not None and basename in parent_node

    def mkdir(self, path):
        node = self._get_node(path, create=True)
        if node is not None:
            return {"status": "success"}
        return {"error": "Could not create directory"}

    def temp_file(self):
        import uuid
        path = f"/tmp/{uuid.uuid4()}"
        self.write_file(path, "")
        return path

    def copy_file(self, src, dst):
        content = self.read_file(src)
        if isinstance(content, dict) and "error" in content:
            return content
        return self.write_file(dst, content)

vfs = VirtualFileSystem()

def read_file(path):
    return vfs.read_file(path)

def write_file(path, content):
    return vfs.write_file(path, content)

def list_dir(path):
    return vfs.list_dir(path)

def append_file(path, content):
    return vfs.append_file(path, content)

def delete_file(path):
    return vfs.delete_file(path)

def file_exists(path):
    return vfs.file_exists(path)

def mkdir(path):
    return vfs.mkdir(path)

def temp_file():
    return vfs.temp_file()

def copy_file(src, dst):
    return vfs.copy_file(src, dst)

# --- Serialization & Data Formats Runtime Helpers ---

def to_json(data):
    """Safely serializes a Python object to a JSON string."""
    try:
        return json.dumps(data, indent=2)
    except TypeError as e:
        return f'{{"error": "Object not serializable", "details": "{e}"}}'

def from_json(json_string):
    """Safely deserializes a JSON string to a Python object."""
    try:
        return json.loads(json_string)
    except json.JSONDecodeError as e:
        return {"error": "Invalid JSON", "details": str(e)}

def write_csv(path, data_list_of_dicts):
    """Writes a list of dictionaries to a CSV file in the virtual FS."""
    if not data_list_of_dicts or not isinstance(data_list_of_dicts, list) or not data_list_of_dicts:
        return {"error": "Invalid data format; expected a non-empty list of dictionaries."}
    headers = data_list_of_dicts[0].keys()
    string_io = io.StringIO()
    writer = csv.DictWriter(string_io, fieldnames=headers)
    writer.writeheader()
    writer.writerows(data_list_of_dicts)
    return vfs.write_file(path, string_io.getvalue())

def read_csv(path):
    """Reads a CSV file from the virtual FS into a list of dictionaries."""
    csv_content = vfs.read_file(path)
    if isinstance(csv_content, dict) and "error" in csv_content:
        return csv_content
    string_io = io.StringIO(csv_content)
    reader = csv.DictReader(string_io)
    return list(reader)

def load_json(source):
    """Loads JSON from a string or a file path in the virtual FS."""
    if source.startswith('/'): # Assume it's a path
        content = vfs.read_file(source)
        if isinstance(content, dict) and "error" in content:
            return content
        return from_json(content)
    return from_json(source)

def dump_json(obj, dest=None):
    """Dumps an object to a JSON string or a file in the virtual FS."""
    json_str = to_json(obj)
    if dest:
        return vfs.write_file(dest, json_str)
    return json_str

def load_yaml(source):
    """Loads YAML from a string or a file path in the virtual FS."""
    try:
        import yaml
    except ImportError:
        return "Error: The 'PyYAML' library is required for this block."

    if source.startswith('/'):
        content = vfs.read_file(source)
        if isinstance(content, dict) and "error" in content:
            return content
        return yaml.safe_load(content)
    return yaml.safe_load(source)

def dump_yaml(obj, dest=None):
    """Dumps an object to a YAML string or a file in the virtual FS."""
    try:
        import yaml
    except ImportError:
        return "Error: The 'PyYAML' library is required for this block."

    yaml_str = yaml.dump(obj)
    if dest:
        return vfs.write_file(dest, yaml_str)
    return yaml_str

def serialize_msgpack(obj):
    """Serializes an object using MessagePack."""
    try:
        import msgpack
        return msgpack.packb(obj, use_bin_type=True)
    except ImportError:
        return "Error: The 'msgpack' library is required for this block."

# --- Database & Persistence Runtime Helpers (SQLAlchemy) ---

try:
    from sqlalchemy import (
        create_engine,
        Table,
        Column,
        Integer,
        String,
        Float,
        Boolean,
        MetaData,
        exc,
        Integer,
    )
except ImportError:
    create_engine = None

# Mapping from string names to SQLAlchemy types
_db_type_map = {
    "INTEGER": Integer,
    "STRING": String,
    "FLOAT": Float,
    "BOOLEAN": Boolean,
}

def db_create_engine(connection_string='sqlite:///:memory:'):
    """Creates a new SQLAlchemy engine."""
    if not create_engine:
        return {"error": "The 'SQLAlchemy' library is required."}
    try:
        engine = create_engine(connection_string)
        return engine
    except Exception as e:
        return {"error": f"Failed to create engine: {e}"}

def db_define_table(table_name, engine, columns_def):
    """Defines a table using SQLAlchemy's core Table object and creates it."""
    if not create_engine:
        return {"error": "The 'SQLAlchemy' library is required."}

    metadata = MetaData()
    sqlalchemy_columns = []
    for col_def in columns_def:
        col_type_str = col_def.get("type", "STRING").upper()
        col_type = _db_type_map.get(col_type_str)
        if not col_type:
            return {"error": f"Unsupported column type: {col_type_str}"}

        sqlalchemy_columns.append(
            Column(
                col_def["name"],
                col_type,
                primary_key=col_def.get("primary_key", False),
            )
        )

    try:
        table = Table(table_name, metadata, *sqlalchemy_columns)
        metadata.create_all(engine)  # Create the table in the database
        return table
    except Exception as e:
        return {"error": f"Failed to define table: {e}"}

def db_execute_statement(engine, statement):
    """Executes a SQLAlchemy statement (insert, update, delete)."""
    if not engine:
        return {"error": "Invalid database engine."}
    try:
        with engine.connect() as connection:
            result = connection.execute(statement)
            connection.commit()
            return {"status": "success", "rows_affected": result.rowcount}
    except exc.SQLAlchemyError as e:
        return {"error": "Database Execution Error", "details": str(e)}

def db_fetch_all(engine, statement):
    """Executes a select statement and fetches all results."""
    if not engine:
        return {"error": "Invalid database engine."}
    try:
        with engine.connect() as connection:
            result = connection.execute(statement)
            # .mappings() returns a list of dict-like objects
            return [row._asdict() for row in result.fetchall()]
    except exc.SQLAlchemyError as e:
        return {"error": "Database Fetch Error", "details": str(e)}

def db_fetch_one(engine, statement):
    """Executes a select statement and fetches the first result."""
    if not engine:
        return {"error": "Invalid database engine."}
    try:
        with engine.connect() as connection:
            result = connection.execute(statement)
            row = result.fetchone()
            if row:
                return row._asdict()
            return None
    except exc.SQLAlchemyError as e:
        return {"error": "Database Fetch Error", "details": str(e)}

# --- Cache Helpers ---

_cache = {}
_cache_ttl = {}

def cache_set(key, value, ttl=None):
    """Sets a value in the cache with an optional time-to-live."""
    import time
    _cache[key] = value
    if ttl:
        _cache_ttl[key] = time.time() + ttl

def cache_get(key):
    """Gets a value from the cache."""
    import time
    if key in _cache_ttl and _cache_ttl[key] < time.time():
        del _cache[key]
        del _cache_ttl[key]
        return None
    return _cache.get(key)

def cache_delete(key):
    """Deletes a value from the cache."""
    if key in _cache:
        del _cache[key]
    if key in _cache_ttl:
        del _cache_ttl[key]

def cache_incr(key, by=1):
    """Increments a value in the cache."""
    value = cache_get(key) or 0
    if isinstance(value, (int, float)):
        _cache[key] = value + by
        return _cache[key]
    return None # Or raise an error

# --- ORM Helpers ---

def orm_model_define(name, fields):
    """Defines an ORM model (dummy implementation)."""
    # In a real scenario, this would interact with an ORM like SQLAlchemy
    return {"name": name, "fields": fields, "__is_orm_model__": True}

def orm_create(session, model, data):
    """Creates a new record using an ORM (dummy implementation)."""
    print(f"ORM: Creating {model.get('name')} with data {data}")
    return {"status": "success"}

def orm_query(session, model, filters):
    """Queries for records using an ORM (dummy implementation)."""
    print(f"ORM: Querying {model.get('name')} with filters {filters}")
    return [{"id": 1, **{f: "sample" for f in model.get("fields", [])}}]

# --- Persistence Helpers ---

def migrate_schema(adapter):
    """Migrates the database schema (dummy implementation)."""
    print(f"Migrating schema with adapter {adapter}")
    return {"status": "success"}

def backup_db(path):
    """Backs up the database to a file (dummy implementation)."""
    print(f"Backing up database to {path}")
    return vfs.write_file(path, "db_backup_content")

def restore_db(path):
    """Restores the database from a file (dummy implementation)."""
    content = vfs.read_file(path)
    print(f"Restoring database from {path} with content: {content}")
    return {"status": "success"}

# --- Logging, Observability & Monitoring Runtime Helpers ---

def log_info(message):
    print(f"INFO: {message}")

def log_warning(message):
    print(f"WARNING: {message}")

def log_error(message):
    print(f"ERROR: {message}")

def metric_increment(name, value=1):
    print(f"METRIC: {name} incremented by {value}")

def trace_start(span_name):
    print(f"TRACE: Start span '{span_name}'")

def trace_stop(span_name):
    print(f"TRACE: Stop span '{span_name}'")

def log_debug(message, data=None):
    """Logs a debug message."""
    if data is not None:
        print(f"DEBUG: {message} | data: {data}")
    else:
        print(f"DEBUG: {message}")

def log_to_file(path, message):
    """Logs a message to a file."""
    # This is a potentially unsafe operation, but it's in a gated suite.
    # In a real scenario, you would want to sanitize the path.
    with open(path, 'a') as f:
        f.write(message + '\n')

def capture_stacktrace():
    """Captures the current stacktrace."""
    import traceback
    return traceback.format_exc()

# --- Testing & Quality Runtime Helpers ---

def run_tests(globals_dict):
    """Discovers and runs all functions in the provided scope that start with 'test_'."""
    results = {"passed": 0, "failed": 0, "errors": 0, "details": []}
    test_functions = [(name, func) for name, func in globals_dict.items() if callable(func) and name.startswith("test_")]
    for name, func in test_functions:
        try:
            func()
            results["passed"] += 1
            results["details"].append({"name": name, "status": "PASSED"})
        except AssertionError as e:
            results["failed"] += 1
            results["details"].append({"name": name, "status": "FAILED", "reason": str(e)})
        except Exception as e:
            results["errors"] += 1
            results["details"].append({"name": name, "status": "ERROR", "reason": str(e)})
    return results

# --- Profiling & Timing Helpers ---

_profiler = None

def timeit_block(func):
    """Times the execution of a block of code."""
    import timeit
    return timeit.timeit(func, number=1)

def profile_start():
    """Starts the profiler."""
    import cProfile
    global _profiler
    _profiler = cProfile.Profile()
    _profiler.enable()

def profile_stop():
    """Stops the profiler and prints the stats."""
    if _profiler:
        _profiler.disable()
        import pstats, io
        s = io.StringIO()
        sortby = pstats.SortKey.CUMULATIVE
        ps = pstats.Stats(_profiler, stream=s).sort_stats(sortby)
        ps.print_stats()
        print(s.getvalue())

def memory_snapshot():
    """Takes a snapshot of memory usage (dummy implementation)."""
    # Requires a library like 'tracemalloc'
    return {"error": "Memory snapshot not implemented."}

def trace_function(func):
    """Traces the execution of a function (dummy implementation)."""
    # Requires a library like 'trace'
    print(f"TRACING function {func.__name__ if hasattr(func, '__name__') else 'anonymous'}")
    return func

# --- CLI Helpers ---

_cli_parser = None

def _get_cli_parser():
    """Initializes and returns a singleton argparse parser."""
    global _cli_parser
    if _cli_parser is None:
        import argparse
        _cli_parser = argparse.ArgumentParser()
    return _cli_parser

def argparse_define(arg):
    """Defines a command-line argument."""
    parser = _get_cli_parser()
    parser.add_argument(arg)

def argparse_parse():
    """Parses command-line arguments."""
    parser = _get_cli_parser()
    return vars(parser.parse_args())

def print_help():
    """Prints the command-line help message."""
    parser = _get_cli_parser()
    parser.print_help()

# --- Enterprise & Specialty Helpers ---

def odoo_connect():
    """Connects to an Odoo instance (dummy implementation)."""
    print("ODOO: Connecting to Odoo")
    return {"status": "connected"}

def odoo_search_create(conn, model, data):
    """Searches for or creates a record in Odoo (dummy implementation)."""
    print(f"ODOO: Searching/creating {model} with data {data}")
    return {"id": 123}

def ros_init_node(name):
    """Initializes a ROS node (dummy implementation)."""
    print(f"ROS: Initializing node '{name}'")

def ros_publish(topic, msg):
    """Publishes a message to a ROS topic (dummy implementation)."""
    print(f"ROS: Publishing to topic '{topic}': {msg}")

def quant_backtest_strategy(strategy, data):
    """Backtests a quantitative trading strategy (dummy implementation)."""
    print(f"FINANCE: Backtesting strategy {strategy} with data {data}")
    return {"pnl": 1000, "sharpe_ratio": 1.5}

# --- Data Science & ML Helpers ---

def _get_pandas():
    try:
        import pandas as pd
        return pd
    except ImportError:
        return None

def _get_matplotlib():
    try:
        import matplotlib.pyplot as plt
        # Ensure matplotlib uses a non-interactive backend
        plt.switch_backend('Agg')
        return plt
    except ImportError:
        return None

def _get_numpy():
    try:
        import numpy as np
        return np
    except ImportError:
        return None

def _get_sklearn():
    try:
        import sklearn
        return sklearn
    except ImportError:
        return None

def quant_get_price_series(ticker):
    """Gets a price series for a financial instrument (dummy implementation)."""
    print(f"FINANCE: Getting price series for {ticker}")
    pd = _get_pandas()
    if not pd:
        return {"error": "The 'pandas' library is required for this block."}
    return pd.DataFrame({'price': [100, 101, 102, 103, 104]})

# --- HTTP Requests (requests) Helpers ---

try:
    import requests
except ImportError:
    requests = None

def _is_domain_allowed_sync(url):
    from urllib.parse import urlparse
    try:
        domain = urlparse(url).netloc
        # Allow requests to localhost without specifying port
        if ':' in domain:
            domain = domain.split(':')[0]
        return domain in ALLOWED_DOMAINS
    except Exception:
        return False

def requests_get(url, headers=None, params=None):
    """Makes a safe GET request to a whitelisted domain."""
    if not requests:
        return {"error": "The 'requests' library is required."}
    if not _is_domain_allowed_sync(url):
        return {"error": "Domain not allowed"}
    try:
        response = requests.get(url, headers=headers, params=params)
        response.raise_for_status()
        try:
            return response.json()
        except ValueError:
            return {"content": response.text}
    except requests.exceptions.RequestException as e:
        return {"error": "Request Failed", "details": str(e)}

def requests_post(url, data=None, json_data=None, headers=None):
    """Makes a safe POST request to a whitelisted domain."""
    if not requests:
        return {"error": "The 'requests' library is required."}
    if not _is_domain_allowed_sync(url):
        return {"error": "Domain not allowed"}
    try:
        response = requests.post(url, data=data, json=json_data, headers=headers)
        response.raise_for_status()
        try:
            return response.json()
        except ValueError:
            return {"content": response.text}
    except requests.exceptions.RequestException as e:
        return {"error": "Request Failed", "details": str(e)}

def requests_put(url, data=None, json_data=None, headers=None):
    """Makes a safe PUT request to a whitelisted domain."""
    if not requests:
        return {"error": "The 'requests' library is required."}
    if not _is_domain_allowed_sync(url):
        return {"error": "Domain not allowed"}
    try:
        response = requests.put(url, data=data, json=json_data, headers=headers)
        response.raise_for_status()
        return {"status_code": response.status_code}
    except requests.exceptions.RequestException as e:
        return {"error": "Request Failed", "details": str(e)}

def requests_delete(url, headers=None):
    """Makes a safe DELETE request to a whitelisted domain."""
    if not requests:
        return {"error": "The 'requests' library is required."}
    if not _is_domain_allowed_sync(url):
        return {"error": "Domain not allowed"}
    try:
        response = requests.delete(url, headers=headers)
        response.raise_for_status()
        return {"status_code": response.status_code}
    except requests.exceptions.RequestException as e:
        return {"error": "Request Failed", "details": str(e)}

# --- FastAPI Web Server Helpers ---

try:
    from fastapi import FastAPI
    import uvicorn
    import threading
except ImportError:
    FastAPI = None
    uvicorn = None
    threading = None

_fastapi_server = None
_fastapi_thread = None

def fastapi_create_app():
    """Creates and returns a new FastAPI application instance."""
    if not FastAPI:
        return None
    return FastAPI()

def fastapi_add_endpoint(app, path, handler, methods):
    """Adds an endpoint to the FastAPI application."""
    if not app or not hasattr(app, "add_api_route"):
        return {"error": "Invalid FastAPI app instance."}

    # The handler needs to be registered with the app
    app.add_api_route(path, handler, methods=methods)
    return handler # Return the original handler, as it's now registered

def fastapi_run_server(app, host='127.0.0.1', port=8000):
    """Runs the FastAPI server in a background thread."""
    global _fastapi_server, _fastapi_thread
    if not uvicorn or not threading:
        return {"error": "The 'uvicorn' library is required to run the server."}

    if _fastapi_thread and _fastapi_thread.is_alive():
        return {"error": "A server is already running."}

    config = uvicorn.Config(app, host=host, port=port, log_level="info")
    _fastapi_server = uvicorn.Server(config)

    _fastapi_thread = threading.Thread(target=_fastapi_server.run)
    _fastapi_thread.start()
    return _fastapi_thread

def fastapi_stop_server():
    """Stops the running FastAPI server."""
    global _fastapi_server, _fastapi_thread
    if _fastapi_server and _fastapi_thread and _fastapi_thread.is_alive():
        _fastapi_server.should_exit = True
        _fastapi_thread.join(timeout=2) # Wait for the thread to finish
        _fastapi_server = None
        _fastapi_thread = None
        return {"status": "Server stopped"}
    return {"error": "No server is running."}

# --- Async IO & Networking Runtime Helpers ---

ALLOWED_DOMAINS = {"api.example.com", "data.example.org", "localhost"}

def _is_domain_allowed(url):
    import httpx
    try:
        domain = httpx.URL(url).host
        return domain in ALLOWED_DOMAINS
    except Exception:
        return False

async def async_http_get(url: str, headers: dict = None):
    """Makes a safe, async GET request to a whitelisted domain."""
    import httpx
    if not _is_domain_allowed(url):
        return {"error": "Domain not allowed"}
    async with httpx.AsyncClient() as client:
        try:
            response = await client.get(url, headers=headers)
            response.raise_for_status()
            try:
                return response.json()
            except ValueError:
                return {"content": response.text}
        except httpx.HTTPStatusError as e:
            return {"error": "HTTP Error", "status_code": e.response.status_code}
        except httpx.RequestError as e:
            return {"error": "Request Error", "details": str(e)}

async def async_http_post(url: str, data: dict = None, json: dict = None, headers: dict = None):
    """Makes a safe, async POST request to a whitelisted domain."""
    import httpx
    if not _is_domain_allowed(url):
        return {"error": "Domain not allowed"}
    async with httpx.AsyncClient() as client:
        try:
            response = await client.post(url, data=data, json=json, headers=headers)
            response.raise_for_status()
            try:
                return response.json()
            except ValueError:
                return {"content": response.text}
        except httpx.HTTPStatusError as e:
            return {"error": "HTTP Error", "status_code": e.response.status_code}
        except httpx.RequestError as e:
            return {"error": "Request Error", "details": str(e)}

# --- Regex Helpers ---

def re_compile(pattern):
    """Compiles a regular expression pattern."""
    import re
    try:
        return re.compile(pattern)
    except re.error as e:
        return {"error": "Invalid regex pattern", "details": str(e)}

def re_search(pattern, string):
    """Searches for a pattern in a string."""
    import re
    if isinstance(pattern, str):
        try:
            pattern = re.compile(pattern)
        except re.error as e:
            return {"error": "Invalid regex pattern", "details": str(e)}
    return pattern.search(string)

def re_match(pattern, string):
    """Matches a pattern at the beginning of a string."""
    import re
    if isinstance(pattern, str):
        try:
            pattern = re.compile(pattern)
        except re.error as e:
            return {"error": "Invalid regex pattern", "details": str(e)}
    return pattern.match(string)

def re_findall(pattern, string):
    """Finds all occurrences of a pattern in a string."""
    import re
    if isinstance(pattern, str):
        try:
            pattern = re.compile(pattern)
        except re.error as e:
            return {"error": "Invalid regex pattern", "details": str(e)}
    return pattern.findall(string)

def re_sub(pattern, repl, string):
    """Substitutes a pattern in a string."""
    import re
    if isinstance(pattern, str):
        try:
            pattern = re.compile(pattern)
        except re.error as e:
            return {"error": "Invalid regex pattern", "details": str(e)}
    return pattern.sub(repl, string)

# --- Itertools Helpers ---

def itertools_chain(iterables):
    """Chains multiple iterables together."""
    from itertools import chain
    return list(chain.from_iterable(iterables))

def itertools_permutations(iterable, r=None):
    """Returns successive r-length permutations of elements."""
    from itertools import permutations
    return list(permutations(iterable, r=r))

def itertools_combinations(iterable, r):
    """Returns r-length subsequences of elements."""
    from itertools import combinations
    return list(combinations(iterable, r))

def itertools_product(*iterables):
    """Returns the cartesian product of iterables."""
    from itertools import product
    return list(product(*iterables))

# --- System Helpers ---

def os_path_join(*paths):
    """Joins one or more path components."""
    import os
    return os.path.join(*paths)

def os_path_exists(path):
    """Checks if a path exists."""
    import os
    return os.path.exists(path)

def sys_argv():
    """Returns the list of command-line arguments."""
    import sys
    return sys.argv

def sys_platform():
    """Returns the platform identifier."""
    import sys
    return sys.platform

def os_path_basename(path):
    """Returns the base name of a path."""
    import os
    return os.path.basename(path)

def os_path_dirname(path):
    """Returns the directory name of a path."""
    import os
    return os.path.dirname(path)

def os_path_splitext(path):
    """Splits the extension of a path."""
    import os
    return os.path.splitext(path)

def os_mkdir(path):
    """Creates a directory."""
    import os
    os.mkdir(path)

def os_makedirs(path):
    """Creates a directory and any parent directories."""
    import os
    os.makedirs(path, exist_ok=True)

def os_rename(src, dst):
    """Renames a file or directory."""
    import os
    os.rename(src, dst)

def os_path_isfile(path):
    """Checks if a path is a file."""
    import os
    return os.path.isfile(path)

def os_path_isdir(path):
    """Checks if a path is a directory."""
    import os
    return os.path.isdir(path)

def df_load_csv(path):
    """Loads a DataFrame from a CSV file."""
    pd = _get_pandas()
    if not pd:
        return {"error": "The 'pandas' library is required for this block."}
    return pd.read_csv(path)

def df_head(df, n):
    """Returns the first n rows of a DataFrame."""
    if df is None: return None
    return df.head(n)

def df_filter(df, condition):
    """Filters a DataFrame based on a condition."""
    if df is None: return None
    return df[condition(df)]

def df_groupby_agg(df, cols, ops):
    """Groups a DataFrame and aggregates the results."""
    if df is None: return None
    return df.groupby(cols).agg(ops)

def df_merge(left_df, right_df, how, on):
    """Merges two DataFrames."""
    pd = _get_pandas()
    if not pd:
        return {"error": "The 'pandas' library is required for this block."}
    if left_df is None or right_df is None: return None
    return pd.merge(left_df, right_df, how=how, on=on)

def df_to_dict_list(df, format):
    """Converts a DataFrame to a dictionary or list of records."""
    if df is None: return None
    if format == 'to_dict':
        return df.to_dict()
    else:
        return df.to_dict('records')

def df_apply(df, fn):
    """Applies a function to a DataFrame."""
    if df is None: return None
    return df.apply(fn)

def array_create_from_list(lst):
    """Creates a numpy array from a list."""
    np = _get_numpy()
    if not np:
        return {"error": "The 'numpy' library is required for this block."}
    return np.array(lst)

def array_shape(arr):
    """Returns the shape of an array."""
    if arr is None: return None
    return arr.shape

def array_reshape(arr, shape):
    """Reshapes an array."""
    if arr is None: return None
    return arr.reshape(shape)

def array_sum(arr):
    """Calculates the sum of an array."""
    if arr is None: return None
    return arr.sum()

def array_mean(arr):
    """Calculates the mean of an array."""
    if arr is None: return None
    return arr.mean()

def array_slice(arr, indices):
    """Slices an array using indices."""
    if arr is None: return None
    return arr[indices]

def array_dot(arr1, arr2):
    """Calculates the dot product of two arrays."""
    np = _get_numpy()
    if not np:
        return {"error": "The 'numpy' library is required for this block."}
    if arr1 is None or arr2 is None: return None
    return np.dot(arr1, arr2)

def model_define(type, params):
    """Defines a machine learning model."""
    sklearn = _get_sklearn()
    if not sklearn:
        return {"error": "The 'scikit-learn' library is required for this block."}

    # This is a simplified implementation. A real one would be more robust.
    from sklearn import linear_model, tree, ensemble
    models = {
        'LinearRegression': linear_model.LinearRegression,
        'DecisionTreeClassifier': tree.DecisionTreeClassifier,
        'RandomForestClassifier': ensemble.RandomForestClassifier,
    }
    model_class = models.get(type)
    if not model_class:
        return {"error": f"Model type '{type}' not supported."}
    return model_class(**params)

def model_train(model, x, y):
    """Trains a machine learning model."""
    if model is None: return
    model.fit(x, y)

def model_predict(model, x):
    """Makes predictions with a machine learning model."""
    if model is None: return None
    return model.predict(x)

def model_save(model, path):
    """Saves a machine learning model to a file."""
    try:
        import joblib
        joblib.dump(model, path)
    except ImportError:
        print("Error: The 'joblib' library is required to save models.")

def model_load(path):
    """Loads a machine learning model from a file."""
    try:
        import joblib
        return joblib.load(path)
    except ImportError:
        return "Error: The 'joblib' library is required to load models."

def model_eval(metrics):
    """Evaluates a machine learning model (dummy implementation)."""
    print(f"Evaluating model with metrics: {metrics}")
    return {"accuracy": 0.95}

def plot_line(x, y):
    """Creates a line plot."""
    plt = _get_matplotlib()
    if not plt:
        return "Error: The 'matplotlib' library is required for this block."
    plt.plot(x, y)
    plt.show()

def plot_hist(data, bins):
    """Creates a histogram."""
    plt = _get_matplotlib()
    if not plt:
        return "Error: The 'matplotlib' library is required for this block."
    plt.hist(data, bins=bins)
    plt.show()

def plot_scatter(x, y):
    """Creates a scatter plot."""
    plt = _get_matplotlib()
    if not plt:
        return "Error: The 'matplotlib' library is required for this block."
    plt.scatter(x, y)
    plt.show()

def df_dropna(df, axis, how):
    """Removes missing values from a DataFrame."""
    if df is None: return None
    return df.dropna(axis=int(axis), how=how)

def df_fillna(df, value):
    """Fills missing values in a DataFrame."""
    if df is None: return None
    return df.fillna(value)

def df_select_column(df, col):
    """Selects a single column from a DataFrame."""
    if df is None: return None
    return df[col]

def df_loc(df, rows, cols):
    """Selects rows and columns by label."""
    if df is None: return None
    return df.loc[rows, cols]

def df_iloc(df, rows, cols):
    """Selects rows and columns by position."""
    if df is None: return None
    return df.iloc[rows, cols]

def df_shape(df):
    """Returns the shape of a DataFrame."""
    if df is None: return None
    return df.shape

def df_dtypes(df):
    """Returns the data types of a DataFrame."""
    if df is None: return None
    return df.dtypes

def df_value_counts(df, col):
    """Counts unique values in a column."""
    if df is None: return None
    return df[col].value_counts()

def df_corr(df):
    """Computes the correlation of columns in a DataFrame."""
    if df is None: return None
    return df.corr()

def df_concat(dfs, axis):
    """Concatenates multiple DataFrames."""
    pd = _get_pandas()
    if not pd:
        return {"error": "The 'pandas' library is required for this block."}
    return pd.concat(dfs, axis=int(axis))

def df_drop(df, labels, axis):
    """Drops specified labels from rows or columns."""
    if df is None: return None
    return df.drop(labels=labels, axis=int(axis))

def df_rename(df, mapper, axis):
    """Renames columns or index labels."""
    if df is None: return None
    return df.rename(mapper=mapper, axis=axis)

def plot_bar(x, y):
    """Creates a bar chart."""
    plt = _get_matplotlib()
    if plt:
        plt.bar(x, y)

def plot_figure(width, height):
    """Creates a new figure with a specific size."""
    plt = _get_matplotlib()
    if plt:
        plt.figure(figsize=(width, height))

def plot_grid(visible):
    """Configures the grid lines."""
    plt = _get_matplotlib()
    if plt:
        plt.grid(visible)

def plot_legend():
    """Displays the legend on the current plot."""
    plt = _get_matplotlib()
    if plt:
        plt.legend()

def plot_savefig(path):
    """Saves the current figure to a file."""
    plt = _get_matplotlib()
    if plt:
        plt.savefig(path)

def plot_set_title(title):
    """Sets the title of the current plot."""
    plt = _get_matplotlib()
    if plt:
        plt.title(title)

def plot_set_xlabel(label):
    """Sets the x-axis label of the current plot."""
    plt = _get_matplotlib()
    if plt:
        plt.xlabel(label)

def plot_set_ylabel(label):
    """Sets the y-axis label of the current plot."""
    plt = _get_matplotlib()
    if plt:
        plt.ylabel(label)

def plot_subplot(row, col, index):
    """Adds a subplot to the current figure."""
    plt = _get_matplotlib()
    if plt:
        plt.subplot(row, col, index)

def plot_xlim(left, right):
    """Sets the x-axis limits."""
    plt = _get_matplotlib()
    if plt:
        plt.xlim(left, right)

def plot_ylim(bottom, top):
    """Sets the y-axis limits."""
    plt = _get_matplotlib()
    if plt:
        plt.ylim(bottom, top)

# --- Pillow (PIL) Helpers ---

try:
    from PIL import Image, ImageDraw, ImageFilter
except ImportError:
    Image = None
    ImageDraw = None
    ImageFilter = None

def pillow_image_create(mode, size, color):
    """Creates a new image."""
    if not Image:
        return "Error: The 'Pillow' library is required."
    return Image.new(mode, size, color)

def pillow_draw_line(image, start, end, fill, width):
    """Draws a line on an image."""
    if not ImageDraw:
        return "Error: The 'Pillow' library is required."
    draw = ImageDraw.Draw(image)
    draw.line([start, end], fill=fill, width=width)

def pillow_draw_rectangle(image, xy, fill, outline, width):
    """Draws a rectangle on an image."""
    if not ImageDraw:
        return "Error: The 'Pillow' library is required."
    draw = ImageDraw.Draw(image)
    draw.rectangle(xy, fill=fill, outline=outline, width=width)

def pillow_draw_ellipse(image, xy, fill, outline, width):
    """Draws an ellipse on an image."""
    if not ImageDraw:
        return "Error: The 'Pillow' library is required."
    draw = ImageDraw.Draw(image)
    draw.ellipse(xy, fill=fill, outline=outline, width=width)

def pillow_draw_text(image, text, position, fill):
    """Draws text on an image."""
    if not ImageDraw:
        return "Error: The 'Pillow' library is required."
    draw = ImageDraw.Draw(image)
    draw.text(position, text, fill=fill)

def pillow_image_filter(image, filter_name):
    """Applies a filter to an image."""
    if not ImageFilter:
        return "Error: The 'Pillow' library is required."
    filter_map = {
        'BLUR': ImageFilter.BLUR,
        'CONTOUR': ImageFilter.CONTOUR,
        'DETAIL': ImageFilter.DETAIL,
        'EDGE_ENHANCE': ImageFilter.EDGE_ENHANCE,
        'EDGE_ENHANCE_MORE': ImageFilter.EDGE_ENHANCE_MORE,
        'EMBOSS': ImageFilter.EMBOSS,
        'FIND_EDGES': ImageFilter.FIND_EDGES,
        'SHARPEN': ImageFilter.SHARPEN,
        'SMOOTH': ImageFilter.SMOOTH,
        'SMOOTH_MORE': ImageFilter.SMOOTH_MORE,
    }
    filter_to_apply = filter_map.get(filter_name)
    if filter_to_apply:
        return image.filter(filter_to_apply)
    return image

# --- BeautifulSoup Helpers ---

try:
    from bs4 import BeautifulSoup
except ImportError:
    BeautifulSoup = None

def beautifulsoup_parse_html(html, parser):
    """Parses HTML content."""
    if not BeautifulSoup:
        return "Error: The 'BeautifulSoup4' library is required."
    return BeautifulSoup(html, parser)

def beautifulsoup_find(soup, tag, attrs):
    """Finds the first matching element."""
    if not soup: return None
    return soup.find(tag, attrs=attrs)

def beautifulsoup_find_all(soup, tag, attrs, limit):
    """Finds all matching elements."""
    if not soup: return []
    return soup.find_all(tag, attrs=attrs, limit=limit)

def beautifulsoup_get_text(element):
    """Gets the text content of an element."""
    if not element: return ""
    return element.get_text()

def beautifulsoup_get_attribute(element, attribute):
    """Gets the value of an attribute."""
    if not element: return ""
    return element.get(attribute, "")